### ISSUE TITLE
1.17.x support?

### ISSUE THREAD

**Issue by Grossley** [Meeples10/MCResourceAnalyzer#1]
Hello! I came across your work while researching ore distribution. I am working on a 1.17 data pack to greatly increase the caving/mineable areas, as 1.17 has increased its possible world heights by a wide margin. Through anecdotal evidence it seems the ore density has dropped precipitously but I cannot confirm it, and I need information on both quantity of ores and their distribution (other tools can only give me the quantity). If MCResourceAnalyzer can do what I need to do for 1.17 it would be very helpful for me in my development of this data pack. Does it support it and, if not, could support be added in the future? Please let me know when you can! 

Update: I tested it on my 1.17 world, it only seems to be analyzing the 0-255 portion

**Comment by Meeples10** [comment]
Sorry for the late reply. MCResourceAnalyzer does not currently support world heights other than 256 blocks, but I plan to add support after 1.18 is released. I would prefer to wait until then in case the chunk NBT format changes during the snapshots.

**Comment by Meeples10** [comment]
Closed by  275b52f.
