### ISSUE TITLE
Missing Preview Image in Minecraft 1.18 Resource Distribution

### ISSUE THREAD

**Issue by bearaujus** [Meeples10/MCResourceAnalyzer#3]
Hello, kind to fix these issue below very helpful for me..
![image](https://user-images.githubusercontent.com/64161364/162250021-b690709c-eadf-4dc8-99f2-f0ddb30b0ee5.png)

I'm going to build huge item sorter.. But I need the block ratio distribution overview for item placement in my sorting system.

Thanks, hope fixed asap ! ;)
I'm going to put block that was generated >= 10.000.000 in my big boys :D

**Comment by Meeples10** [comment]
Sorry, I'll try to put them up by tomorrow. Apparently I forgot and never finished the rest of the graphs.

**Comment by bearaujus** [comment]
Alright.. Thanks again ! :D

Already putted 7 big modules, because in my previous item sorter the junk chest is filled by block like netherrack, sand, stone, etc..
Before finishing the decoration.. I need fixed block placed there.. (Because maybe I need to add more modules)
![2022-04-07_23 23 24](https://user-images.githubusercontent.com/64161364/162251297-020043be-6321-4956-b88c-76a2128424e6.png)

**Comment by Meeples10** [comment]
By ratio do you mean how common each block is overall? If you do, [this table](https://meeples10.github.io/resource-distribution/1.18/overworld.html) is sorted by how common the block is. The far right column is the ratio of the number of each block versus the total number of blocks in the world.

**Comment by bearaujus** [comment]
Yup I saw that table.. But its hard to read xD 
Need statistical chart like in overview for clear view.. That was so good !

**Comment by Meeples10** [comment]
The charts actually just show the Y levels that certain blocks are most common at. If it included every block in the table, it would be too crowded to read.

Here is a more reasonable table you might be able to use, sorted in order of commonness:

|Block|Ratio (Count/Total)|
|:-:|---------------------|
|deepslate|41.95778737|
|stone|33.49126125|
|air|N/A|
|water|6.857847195|
|tuff|2.521603079|
|bedrock|2.39848441|
|andesite|2.25173911|
|diorite|2.142183967|
|granite|2.086206083|
|dirt|1.874964855|
|gravel|1.219222431|
|grass_block|0.361957237|
|clay|0.269750877|
|sand|0.255678854|
|copper_ore|0.213747859|
|coal_ore|0.200700146|
|lava|0.151422116|
|packed_ice|0.119771676|
|iron_ore|0.113618563|
|oak_leaves|0.112885577|
|cave_air|N/A|
|sandstone|0.090630292|
|dripstone_block|0.085360757|
|deepslate_redstone_ore|0.074076694|
|terracotta|0.06941354|
|deepslate_iron_ore|0.068829287|
|spruce_leaves|0.054575122|
|smooth_basalt|0.052494082|
|moss_block|0.051006963|
|kelp_plant|0.050283305|
|deepslate_gold_ore|0.048516397|
|birch_leaves|0.044656768|
|calcite|0.042507445|
|orange_terracotta|0.040239625|
|grass|0.036732236|
|deepslate_diamond_ore|0.033090779|
|amethyst_block|0.033038713|
|snow|0.031958981|
|deepslate_lapis_ore|0.030970827|
|tall_seagrass|0.02953714|
|brown_terracotta|0.025930352|
|lapis_ore|0.022430341|
|dark_oak_leaves|0.019618017|
|vine|0.019177761|
|deepslate_copper_ore|0.018879258|
|pointed_dripstone|0.018695228|
|snow_block|0.018391493|
|jungle_leaves|0.017895711|
|light_gray_terracotta|0.01741814|
|seagrass|0.017285491|
|yellow_terracotta|0.014904431|
|white_terracotta|0.014387842|
|ice|0.013890694|
|oak_planks|0.010400623|
|gold_ore|0.009908561|
|kelp|0.009556252|
|oak_log|0.00940873|
|spruce_log|0.008354565|
|red_terracotta|0.008307901|
|dark_oak_log|0.007574226|
|bamboo|0.007225561|
|podzol|0.007109265|
|cave_vines_plant|0.006694247|
|glow_lichen|0.006692554|
|oak_fence|0.00622196|
|redstone_ore|0.006084836|
|cobblestone|0.00599694|
|birch_log|0.00548982|
|tall_grass|0.004584058|
|jungle_log|0.004469018|
|acacia_leaves|0.003883562|
|red_sand|0.003700646|
|cave_vines|0.0036866|
|moss_carpet|0.003180289|
|budding_amethyst|0.002989986|
|mossy_cobblestone|0.002898347|
|infested_deepslate|0.002891418|
|fern|0.00277295|
|coarse_dirt|0.00259316|
|magma_block|0.002488976|
|rail|0.002360112|
|cobweb|0.001986817|
|blue_ice|0.001900575|
|infested_stone|0.00177562|
|powder_snow|0.00175927|
|deepslate_coal_ore|0.001741733|
|prismarine|0.00152313|
|prismarine_bricks|0.001520604|
|mycelium|0.001307199|
|rooted_dirt|0.001234707|
|bubble_column|0.001032069|
|diamond_ore|0.000925787|
|azalea|0.000890973|
|red_mushroom_block|0.000840845|
|netherrack|0.000767046|
|large_fern|0.000745652|
|big_dripleaf_stem|0.00066078|
|dirt_path|0.000569905|
|big_dripleaf|0.000559435|
|flowering_azalea|0.00050876|
|dead_bush|0.000460084|
|acacia_log|0.000459433|
|dandelion|0.000440705|
|tube_coral_block|0.000438383|
|brain_coral_block|0.000435511|
|bubble_coral_block|0.000434645|
|horn_coral_block|0.0004337|
|fire_coral_block|0.000432136|
|chain|0.000370101|
|raw_iron_block|0.00032195|
|brown_mushroom_block|0.000309681|
|dark_oak_planks|0.000294769|
|raw_copper_block|0.000289324|
|small_dripleaf|0.000277022|
|emerald_ore|0.00027595|
|horn_coral_wall_fan|0.000271959|
|bubble_coral_wall_fan|0.000271737|
|brain_coral_wall_fan|0.000270903|
|tube_coral_wall_fan|0.000270852|
|fire_coral_wall_fan|0.000270203|
|poppy|0.000247595|
|azure_bluet|0.00019561|
|oak_stairs|0.000185416|
|sunflower|0.000160978|
|spruce_planks|0.000156714|
|lily_pad|0.000155736|
|mushroom_stem|0.000141225|
|bone_block|0.000139473|
|medium_amethyst_bud|0.000131919|
|small_amethyst_bud|0.000131343|
|amethyst_cluster|0.000130495|
|large_amethyst_bud|0.000130417|
|wall_torch|0.000126825|
|brown_mushroom|0.00012109|
|birch_planks|0.000120669|
|sea_pickle|0.000119738|
|azalea_leaves|0.000111864|
|sugar_cane|0.00010874|
|mossy_stone_bricks|0.000107496|
|cornflower|0.000101221|
|chest|9.16704E-05|
|lilac|8.47104E-05|
|rose_bush|8.30643E-05|
|peony|0.000081532|
|spore_blossom|7.94185E-05|
|spruce_stairs|7.51849E-05|
|smooth_sandstone|7.47187E-05|
|dark_prismarine|7.36034E-05|
|spawner|7.32214E-05|
|cut_sandstone|6.63884E-05|
|stone_bricks|6.42377E-05|
|oxeye_daisy|0.000061335|
|cocoa|6.04901E-05|
|orange_tulip|5.87115E-05|
|dark_oak_stairs|5.74944E-05|
|white_tulip|5.27519E-05|
|jungle_planks|5.27355E-05|
|red_tulip|5.14626E-05|
|cracked_stone_bricks|5.04381E-05|
|farmland|4.93644E-05|
|dark_oak_fence|4.68843E-05|
|lily_of_the_valley|4.58073E-05|
|allium|4.54406E-05|
|sweet_berry_bush|3.78666E-05|
|brain_coral|3.75613E-05|
|horn_coral|3.75284E-05|
|fire_coral|3.74398E-05|
|tube_coral|3.74058E-05|
|brain_coral_fan|3.73664E-05|
|bubble_coral|3.73643E-05|
|fire_coral_fan|0.000037303|
|bubble_coral_fan|3.72898E-05|
|flowering_azalea_leaves|3.72263E-05|
|tube_coral_fan|3.71869E-05|
|horn_coral_fan|3.70031E-05|
|acacia_stairs|3.56557E-05|
|wheat|3.54379E-05|
|obsidian|3.37206E-05|
|pumpkin|0.000033713|
|acacia_planks|3.20537E-05|
|pink_tulip|3.15896E-05|
|sea_lantern|2.93174E-05|
|melon|0.000029069|
|jungle_stairs|2.30547E-05|
|glass_pane|2.09653E-05|
|cobblestone_stairs|2.00251E-05|
|chiseled_stone_bricks|1.86646E-05|
|red_carpet|1.80276E-05|
|cactus|1.53406E-05|
|spruce_fence|1.52213E-05|
|stone_brick_stairs|1.43939E-05|
|spruce_slab|1.33245E-05|
|hay_block|1.30739E-05|
|spruce_trapdoor|1.24719E-05|
|red_sandstone|1.22639E-05|
|white_carpet|1.16948E-05|
|acacia_wood|1.15536E-05|
|stripped_spruce_log|1.11235E-05|
|polished_granite|1.06758E-05|
|wet_sponge|1.05828E-05|
|stripped_oak_log|1.05281E-05|
|cobblestone_wall|1.03891E-05|
|deepslate_emerald_ore|9.4806E-06|
|acacia_fence|9.3723E-06|
|acacia_slab|8.9728E-06|
|oak_slab|8.8688E-06|
|hanging_roots|8.2165E-06|
|stripped_spruce_wood|7.9188E-06|
|smooth_sandstone_slab|7.6758E-06|
|torch|7.5849E-06|
|oak_door|6.9895E-06|
|stone_brick_slab|6.9206E-06|
|jungle_fence|0.000006902|
|blue_orchid|6.8998E-06|
|oak_trapdoor|6.3755E-06|
|melon_stem|5.9848E-06|
|mossy_stone_brick_slab|5.9125E-06|
|bee_nest|5.4266E-06|
|jungle_slab|5.2821E-06|
|dark_oak_slab|5.1792E-06|
|bookshelf|4.9329E-06|
|carrots|4.5313E-06|
|birch_stairs|4.1876E-06|
|smooth_stone_slab|4.0606E-06|
|sandstone_slab|3.8362E-06|
|birch_fence|3.6458E-06|
|white_wool|3.5265E-06|
|smooth_sandstone_stairs|3.5232E-06|
|gold_block|3.2332E-06|
|spruce_door|3.0985E-06|
|potatoes|3.0778E-06|
|iron_bars|2.9015E-06|
|birch_slab|2.8512E-06|
|mossy_stone_brick_stairs|2.8315E-06|
|ladder|2.8063E-06|
|dark_oak_trapdoor|2.7932E-06|
|chiseled_sandstone|2.6181E-06|
|polished_andesite|0.000002559|
|crying_obsidian|0.000002513|
|white_bed|2.4265E-06|
|sandstone_stairs|2.2405E-06|
|light_gray_wool|2.1824E-06|
|red_mushroom|2.1212E-06|
|sandstone_wall|2.0631E-06|
|infested_stone_bricks|0.000002015|
|yellow_bed|1.9307E-06|
|acacia_door|1.8486E-06|
|stone_slab|0.00000183|
|brown_wall_banner|1.8234E-06|
|yellow_stained_glass_pane|0.000001436|
|smooth_stone|1.4316E-06|
|white_stained_glass_pane|1.3517E-06|
|jungle_trapdoor|1.3375E-06|
|jungle_door|1.3287E-06|
|bricks|1.3057E-06|
|lantern|1.2773E-06|
|cobblestone_slab|1.1886E-06|
|stripped_oak_wood|1.1098E-06|
|black_wool|0.000001065|
|beetroots|1.0639E-06|
|yellow_wool|8.975E-07|
|composter|8.592E-07|
|jungle_button|0.000000799|
|blue_bed|7.596E-07|
|pumpkin_stem|7.081E-07|
|light_blue_terracotta|6.414E-07|
|oak_fence_gate|0.000000637|
|orange_bed|0.000000614|
|bell|5.713E-07|
|green_carpet|5.615E-07|
|dark_oak_sapling|0.000000556|
|water_cauldron|5.494E-07|
|purple_bed|5.396E-07|
|crafting_table|5.341E-07|
|potted_cactus|5.188E-07|
|stripped_acacia_log|4.969E-07|
|light_gray_carpet|4.575E-07|
|furnace|4.498E-07|
|white_wall_banner|4.356E-07|
|red_bed|4.104E-07|
|redstone_wire|3.667E-07|
|purple_glazed_terracotta|3.502E-07|
|lime_bed|3.459E-07|
|yellow_carpet|3.349E-07|
|green_bed|3.229E-07|
|brewing_stand|2.966E-07|
|stone_brick_wall|2.955E-07|
|tnt|2.879E-07|
|blue_carpet|2.868E-07|
|oak_pressure_plate|2.769E-07|
|grindstone|2.703E-07|
|dark_oak_door|2.671E-07|
|cartography_table|0.00000022|
|blast_furnace|2.036E-07|
|mossy_stone_brick_wall|1.981E-07|
|carved_pumpkin|1.937E-07|
|cyan_bed|1.872E-07|
|purple_carpet|1.861E-07|
|stonecutter|1.839E-07|
|light_blue_wool|1.839E-07|
|gray_carpet|1.762E-07|
|iron_door|1.686E-07|
|campfire|1.675E-07|
|potted_dead_bush|1.653E-07|
|acacia_pressure_plate|1.554E-07|
|spruce_wood|0.000000151|
|blue_wool|0.000000151|
|lime_carpet|1.489E-07|
|diorite_wall|1.434E-07|
|brown_wool|1.379E-07|
|barrel|1.281E-07|
|polished_diorite|1.281E-07|
|tripwire|1.204E-07|
|brown_stained_glass_pane|1.204E-07|
|gray_wool|1.127E-07|
|smoker|1.127E-07|
|yellow_glazed_terracotta|1.116E-07|
|diorite_stairs|1.116E-07|
|stone_button|1.105E-07|
|white_glazed_terracotta|0.000000104|
|lever|9.96E-08|
|lectern|9.85E-08|
|tripwire_hook|9.63E-08|
|fletching_table|8.87E-08|
|mossy_cobblestone_stairs|8.65E-08|
|light_blue_carpet|8.54E-08|
|smithing_table|8.32E-08|
|glass|0.000000081|
|redstone_torch|7.88E-08|
|brown_carpet|7.44E-08|
|infested_chiseled_stone_bricks|7.33E-08|
|potted_dandelion|7.22E-08|
|sticky_piston|7.22E-08|
|loom|7.11E-08|
|attached_pumpkin_stem|7.11E-08|
|attached_melon_stem|7.11E-08|
|potted_white_tulip|0.000000069|
|red_wool|6.79E-08|
|cyan_wool|6.24E-08|
|orange_wool|0.000000058|
|cauldron|5.69E-08|
|spruce_wall_sign|5.69E-08|
|green_wool|5.47E-08|
|acacia_fence_gate|5.14E-08|
|dispenser|4.82E-08|
|pink_carpet|0.000000046|
|potted_red_tulip|4.49E-08|
|potted_oxeye_daisy|4.38E-08|
|jack_o_lantern|4.05E-08|
|acacia_sapling|3.72E-08|
|orange_carpet|3.72E-08|
|infested_mossy_stone_bricks|3.72E-08|
|oak_wall_sign|3.61E-08|
|potted_azure_bluet|0.000000035|
|orange_stained_glass_pane|0.000000035|
|magenta_carpet|0.000000035|
|potted_birch_sapling|0.000000035|
|diorite_slab|0.000000035|
|spruce_fence_gate|3.39E-08|
|jungle_fence_gate|3.17E-08|
|potted_red_mushroom|3.17E-08|
|stone_pressure_plate|3.17E-08|
|blue_terracotta|3.17E-08|
|light_gray_wall_banner|2.96E-08|
|orange_glazed_terracotta|2.85E-08|
|potted_blue_orchid|2.85E-08|
|potted_allium|2.74E-08|
|potted_spruce_sapling|2.63E-08|
|black_carpet|2.63E-08|
|infested_cobblestone|2.63E-08|
|repeater|2.41E-08|
|potted_poppy|0.000000023|
|lime_terracotta|0.000000023|
|end_portal_frame|2.08E-08|
|dark_oak_fence_gate|1.97E-08|
|mossy_cobblestone_wall|1.86E-08|
|spruce_pressure_plate|1.86E-08|
|granite_stairs|1.75E-08|
|granite_wall|1.75E-08|
|cyan_carpet|1.31E-08|
|lime_wool|1.31E-08|
|dead_fire_coral_block|1.09E-08|
|mossy_cobblestone_slab|1.09E-08|
|damaged_anvil|8.8E-09|
|black_wall_banner|8.8E-09|
|lapis_block|7.7E-09|
|dead_tube_coral_block|6.6E-09|
|diamond_block|5.5E-09|
|dead_bubble_coral_block|5.5E-09|
|gray_wall_banner|4.4E-09|
|lime_glazed_terracotta|4.4E-09|
|dead_brain_coral_block|3.3E-09|
|dead_horn_coral_block|3.3E-09|
|trapped_chest|1.1E-09|

**Comment by bearaujus** [comment]
Sorry, just found the conclusion.. 
You don't need to rush to fix this issue than :D
![image](https://user-images.githubusercontent.com/64161364/162253701-acedc3b3-d2c8-4b02-b1fe-6c334e5feca8.png)

**Comment by bearaujus** [comment]
Thanks !!

**Comment by Meeples10** [comment]
I've added the missing [graphs for 1.18](https://meeples10.github.io/resource-distribution/1.18/preview.html).
